on:
  schedule:
    - cron: '30 5 * * 1,3'
    - cron: '30 5 * * 2,4'
  
jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: Not on monday or wednesday
        if: github.event.schedule != '30 5 * * 1,3'
        run: echo 'skip this step on monday and wednesday'
      - name: Every time
        run: echo 'this step will always run'