name: Setup repo checkout

on: push

jobs:
  access_repo_files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
      - uses: actions/checkout@v4
    
      - name: List files
        run: ls -R
      
      - name: Read readme.md
        run: cat README.md 
  